class Constants {
  static const List<String> bookCategories = [
    "Fiction",
    "Non-Fiction",
    "Science",
    "Technology",
    "History",
    "Biography",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Romance",
    "Horror",
    "Self-Help",
    "Poetry",
    "Comics",
    "Graphic Novels",
    "Science Fiction",
    "Adventure",
    "Philosophy",
    "Psychology",
    "Religion",
    "Spirituality",
    "Health & Wellness",
    "Education",
    "Business",
    "Finance",
    "Politics",
    "Law",
    "Sports",
    "Travel",
    "Cooking",
    "Art & Photography",
    "Music",
    "Mathematics",
    "Programming",
    "Engineering",
    "Medical",
    "Anthropology",
    "Linguistics",
    "Economics",
    "Astronomy",
    "Mythology",
    "Environment",
    "Classic Literature",
    "Young Adult",
    "Children's Books",
  ];
}
